version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    working_dir: /var/www
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app/public:/var/www/public
      - ./nginx/logs:/var/log/nginx/
    networks:
      - app

  app:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www
    networks:
      - app

  db:
    image: mariadb
    container_name: app-db
    restart: always
    environment:
          MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}
          MARIADB_DATABASE: ${MARIADB_DATABASE}
          MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
          SERVICE_NAME: db
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app

networks:
  app:
    driver: bridge